pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: "https://github.com/Korolev731/jenkins.git", credentialsId: '2a34e1ef-f8e1-425a-999a-49d5919acfce' // здесь добавляем credentialsId и указываем наш ID.
            }
        }
        stage('Deploy') {
            steps {
                sh 'ansible --version'
                sh 'ansible-playbook playbook.yml'
            }
        }
    }
}
